spring.application.name=cinevault-recommendation-service
server.port=8081

# Base configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/cinevault_recommendations_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=${DB_PASS}
logging.level.org.hibernate.persister.entity=ERROR


#JPA Properties
spring.jpa.properties.hibernate.format_sql = TRUE
#spring.jpa.open-in-view=false

###Logging Levels
# Disable the default loggers
logging.level.org = WARN
logging.level.blog = WARN

#Show SQL executed with parameter bindings
logging.level.sql = DEBUG

spring.mvc.hiddenmethod.filter.enabled=true
